### ISSUE TITLE
A name parameter is required to create a storage

### ISSUE THREAD

**Issue by obennaci** [iotacss/iotaplate#1]
Hi,
Using the command outputs the following error:

`AssertionError: A name parameter is required to create a storage`

OS: Linux
Node: v7.10
Yarn: v0.24.6

---
EDIT:
This seems to happen only when I try it with [JeffreyWay/laravel-mix](https://github.com/JeffreyWay/laravel-mix)

**Comment by JorenRothman** [comment]
Same problem over here only i cant use it at all.

**Comment by harby** [comment]
@jorenrothman what's your node version? Also, are you getting the issue with laravel-mix or in general? Trying to reproduce it.

**Comment by JorenRothman** [comment]
@harby solved my problem didn't had a package.json in my root folder

**Comment by harby** [comment]
@Gostwow do you have a package.json to your application's root folder?

**Comment by obennaci** [comment]
@harby Yes

After a bit of research, it seems like Yeoman has issues with `package.json` files that don't have a `name` property. Adding it solved the issue.

**Comment by harby** [comment]
Ok great! So, I close this issue.
